export const postS = [
    { id: 1, title: "hello0", text: "hello world" },
    { id: 2, title: "hello1", text: "I do not now about my switheart" },
    { id: 3, title: "hello2", text: "hello world" },
    { id: 4, title: "1hello3", text: "hello world" },
    { id: 5, title: "3hello4", text: "I do not now about my switheart" },
    { id: 6, title: "2hello5", text: "hello world" },
    { id: 7, title: "4hello6", text: "hello world" },
    { id: 8, title: "5hello7", text: "I do not now about my switheart" },
    { id: 9, title: "635hello8", text: "hello world" },
    { id: 10, title: "346hello9", text: "hello world" },
    { id: 11, title: "6hello10", text: "I do not now about my switheart" },
    { id: 12, title: "4hello11", text: "hello world" },
    { id: 13, title: "434hello12", text: "hello world" },
    { id: 14, title: "345hello13", text: "I do not now about my switheart" },
    { id: 15, title: "q4hello14", text: "hello world" },
  ];